# Test your FastAPI endpoints


GET http://127.0.0.1:8000/
Accept: application/json

> {% console.log(response.body); %}

###

POST http://127.0.0.1:8000/create_room
Accept: application/json
Content-Type: application/json

> {% console.log(response.body); %}

###



